### ISSUE TITLE
I can't seem to get this to work with react-autosize-textarea

### ISSUE THREAD

**Issue by jpsear** [webscopeio/react-textarea-autocomplete#150]
I'm a little confused. I've scoured the issues and read the docs a million times, but can't seem to find a combination that works.

This is what I've got:

```js
import Textarea from 'react-autosize-textarea'
import ReactTextareaAutoComplete from '@webscopeio/react-textarea-autocomplete'

// ...

render () {
  const AutoSizeTextArea = () => (
    <Textarea styleName='text-area' . id={this.props.id} />
  )

  return (
    <ReactTextareaAutoComplete
      textAreaComponent={{ component: AutoSizeTextArea, ref: 'innerRef' }} />
  )
}
```

I've omited a few props, such as `trigger` etc, as my `ReactTextareaAutoComplete` is working fine standalone.

**Comment by jukben** [comment]
Hey,

I guess it should be

```
<ReactTextareaAutoComplete
      textAreaComponent={{ component: Textarea, ref: 'innerRef' }} />
```

Have you tried that?

**Comment by jpsear** [comment]
Hey, cheers for the reply.

Yup, tried it. The autocomplete still works nicely, but the autoresize does not work.

**Comment by jukben** [comment]
Got it. Apparently there is some breaking change in `react-autosize-textarea`. Could you please test it out with version 6.0? I got it work.

**Comment by jpsear** [comment]
Sure no worries — I'll report back

**Comment by jukben** [comment]
I see. Version 7.0 uses (and supports only) React.createRef approach – this component does not. So you have to use version 6.0. Sorry about it!

**Comment by jukben** [comment]
Closing for now because I believe they should support both approaches, function and React.createRef.

**Comment by jpsear** [comment]
No probs. Cheers for taking a look :)

**Comment by jpsear** [comment]
Darn, it's not working on version 6.0.0 for me

**Comment by jukben** [comment]
Could you please elaborate on it more? 🤔 

Please check it out this example branch https://github.com/webscopeio/react-textarea-autocomplete/tree/example/react-autosize-textarea

**Comment by jpsear** [comment]
Thanks for the branch. I've glanced over it and my setup looks the same. I will test later and come back to you.

**Comment by AndreasPresthammer** [comment]
Managed to it working with react react-textarea-autosize (NB! not react-autosize-textarea - although you may get this to work aswell)

```
const ResizeTextArea = React.forwardRef((props: any, ref) => {
  return (<TextareaAutosize inputRef={ref} {...props} minRows={3} maxRows={40} />);
});
```
and
```
<ReactTextareaAutocomplete
      textAreaComponent={ResizeTextArea}
...
 />

```

**Comment by grahammcculloch** [comment]
FWIW, having examined the source code for `react-textarea-autocomplete` and `react-autosize-textarea` I concluded they are now incompatible as of v7.0.0 of `react-autosize-textarea` as the [`TextareaAutosize` component expects a ref object rather than a function](https://github.com/buildo/react-autosize-textarea/blob/v7.0.0/src/TextareaAutosize.tsx#L68) for the textarea ref whereas [`react-textarea-autocomplete` provides a function that accepts a ref and returns nothing](https://github.com/webscopeio/react-textarea-autocomplete/blob/v4.6.3/src/Textarea.jsx#L980-L984).

So I switched to using `react-textarea-autosize` which works great - thanks @AndreasPresthammer for the tip.
