### ISSUE TITLE
If the editor is at the bottom of the window, better open it upwards instead. 

### ISSUE THREAD

**Issue by jukben** [webscopeio/react-textarea-autocomplete#37]
Discussion: #33

> The dropdown always opens downwards, but sometimes, if the editor is at the bottom of the window, better open it upwards instead. 

> That's really good feedback. I'd love to implement this. Could be handy and really bulletproof functionality. Also, it would be cool to support also other directions. (right - left)

Something like https://popper.js.org/#example3, maybe we should use it. I need to dig more into it.

**Comment by BenoKop** [comment]
Is there something for this issue ?

**Comment by jukben** [comment]
@BenoKop this feature is still pending. Are you interested in sending PR for it?

**Comment by jukben** [comment]
This going to be shipped as 4.0.0! 🚀 Finally, ~1 year later. 🙉

**Comment by BenoKop** [comment]
Nice ! When for the 4.0.0 ? I'm maintaining the project that I wrote ~1 year ago :D

**Comment by jukben** [comment]
@BenoKop 
Haha! It's already here https://github.com/webscopeio/react-textarea-autocomplete/releases 🚀 

Also in the PR (https://github.com/webscopeio/react-textarea-autocomplete/pull/111) there is more about how it works, actually it's on by default – by default it should prevent to overflow from body element. I hope it works fine for you! 

Can you try it out and write me feedback?

**Comment by BenoKop** [comment]
Cool !
I'm not sure I can try it today :s but I will try I when I can !

**Comment by jukben** [comment]
What's the boundaries element? Body? Are you able to reproduce it codepen? 🙏

**Comment by andypearson** [comment]
@jukben I don't see any errors at all. Switching to using a CSS selector doesn't seem to help. I did have `movePopupAsYouType` enabled but turning that off doesn't seem to make any difference either.

Shall I try and make a Codepen that reproduces the setup I have?

**Comment by jukben** [comment]
@andypearson yes, please do. I've tried to give it a shot, but for me, it works https://codepen.io/jukben/pen/rovaLM check it out.

**Comment by andypearson** [comment]
@jukben done: https://codepen.io/andy-pearson/pen/vvRLRP

This mimics the way I am using the component quite well.

It's weird, because comparing mine and yours, it feels like the only difference with mine is the `overflow-y: auto` and `height: 300px` in the CSS but even if I remove those the dropdown doesn't position itself like it does in your example. Potential user error alert! :D

**Comment by andypearson** [comment]
@jukben I'll give 4.1.0 a try next week when I'm back at work, will keep you posted!

Don't think I'm using the option you removed so should be all good :)

Cheers again for your hard work on this awesome project!

**Comment by andypearson** [comment]
@jukben I noticed that my CodePen had started working so I was quite excited, but on upgrading to 4.2.2 in my project the autocomplete still won't appear in the correct spot. :(

I went back to the CodePen and updated it until I could repeat the problem:
![large gif 696x614](https://user-images.githubusercontent.com/857/51392793-04885580-1b2e-11e9-817b-b3cff2db05c6.gif)

Here's the example URL again: https://codepen.io/andy-pearson/full/vvRLRP

Now the number of items appears randomly, there seems to be a race condition where the autocomplete doesn't quite know its own size before doing the positioning calculations.

Interestingly, this example also crashes Firefox fairly consistently with the following error:

```
RTA: dataProvider fails: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

I think the trick would be to change `_calculatePosition` so that it sets the required styles directly using the DOM APIs, rather than getting React to do it with setState. Shall I try and have a go at making that change? Feel like I'm asking a lot without actually contributing!
